### ISSUE TITLE
Translation is occasionally broken

### ISSUE THREAD

**Issue by ml-milan-vit** [monstar-lab-oss/deepl-for-slack-elixir#6]
Likely culprit might be if message begins with the tag `@here`. Most of the message doesn’t get translated, only last part (last sentence, last few words, etc.) get translated.

Showcases of the bug:
- https://monstarlab.slack.com/archives/C91EVG73P/p1625647278255000?thread_ts=1625647028.254300&cid=C91EVG73P
- https://monstarlab.slack.com/archives/CTLV2JZT9/p1625644701098300

**Comment by Cellane** [comment]
This should be fixed in Deep Thought 2.0
